name: nwn
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.24.3
  - networkx=3.1
  - scipy=1.10.1
  - Shapely=2.0.4
  - matplotlib=3.7.1
  - ipykernel
  - line_profiler
  - joblib
  - pip
  - pytest
